version: "2"
services:
    dev-mysql:
        image: mysql:5.7
        restart: always
        ports:
            - 3306:3306
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - backend-network
        environment:
            MYSQL_ROOT_PASSWORD: "pass123"
    dev-redis:
        image: redis:5
        restart: always
        ports:
            - 6379:6379
        volumes:
            - redis-data:/data
        networks:
            - backend-network

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local

networks:
  backend-network:
    driver: bridge